
version: '3'
services:

   app-mapper-1:
    build:
      context: ./Mapper
    ports:
      - "9001:9001"  # Assegna porte univoche ai Mapper
      - "40001:40001"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - MAPPER_PORT=9001
      - HB_PORT=40001
    networks:
      - my-network

   app-mapper-2:
    build:
      context: ./Mapper
    ports:
      - "9002:9002"  # Assegna porte univoche ai Mapper
      - "40002:40002"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - MAPPER_PORT=9002
      - HB_PORT=40002
    networks:
      - my-network

   app-mapper-3:
    build:
      context: ./Mapper
    ports:
      - "9003:9003"  # Assegna porte univoche ai Mapper
      - "40003:40003"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - MAPPER_PORT=9003
      - HB_PORT=40003
    networks:
      - my-network

   app-mapper-4:
    build:
      context: ./Mapper
    ports:
      - "9004:9004"  # Assegna porte univoche ai Mapper
      - "40004:40004"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - MAPPER_PORT=9004
      - HB_PORT=40004
    networks:
      - my-network

   app-mapper-5:
    build:
      context: ./Mapper
    ports:
      - "9005:9005"  # Assegna porte univoche ai Mapper
      - "40005:40005"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - MAPPER_PORT=9005
      - HB_PORT=40005
    networks:
      - my-network

   app-reducer-1:
    build:
      context: ./Reducer
    volumes:
      - ./configuration.json:/Reducer/constants/configuration.json
    ports:
      - "10001:10001"  # Assegna porte univoche ai reducer
      - "41001:41001"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - REDUCER_PORT=10001
      - HB_PORT=41001
    networks:
      - my-network

   app-reducer-2:
    build:
      context: ./Reducer
    volumes:
      - ./configuration.json:/Reducer/constants/configuration.json
    ports:
      - "10002:10002"  # Assegna porte univoche ai reducer
      - "41002:41002"  # Porta univoca per servizio di HeartBeat
    environment:
      - TZ=Europe/Rome
      - REDUCER_PORT=10002
      - HB_PORT=41002
    networks:
      - my-network

networks:
  my-network:
