
version: '3'
services:
   app-master:
    build:
      context: ./Master
    volumes:
      - ./output:/Master/output
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network
   app-mapper-1:
    build:
      context: ./Mapper
    ports:
      - "9000:9000"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-mapper-2:
    build:
      context: ./Mapper
    ports:
      - "9001:9001"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-mapper-3:
    build:
      context: ./Mapper
    ports:
      - "9002:9002"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-mapper-4:
    build:
      context: ./Mapper
    ports:
      - "9003:9003"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-mapper-5:
    build:
      context: ./Mapper
    ports:
      - "9004:9004"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-mapper-6:
    build:
      context: ./Mapper
    ports:
      - "9005:9005"  # Assegna porte univoche ai mapper
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-reducer-1:
    build:
      context: ./Reducer
    ports:
      - "10000:10000"  # Assegna porte univoche ai reducer
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

   app-reducer-2:
    build:
      context: ./Reducer
    ports:
      - "10001:10001"  # Assegna porte univoche ai reducer
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

networks:
  my-network:
