version: '3'
services:
  app-master:
    build:
      context: ./Master
    volumes:
      - ./output:/Master/output
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network
  app-mapper:
    build:
      context: ./Mapper
    ports:
      - "9000:9000"
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network
  app-reducer:
    build:
      context: ./Reducer
    ports:
      - "9001:9001"
    environment:
      - TZ=Europe/Rome
    networks:
      - my-network

networks:
  my-network:
