//reducer-proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v4.23.4
// source: reducer.proto

package reducer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReducerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId         int32     `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PageRankShares []float32 `protobuf:"fixed32,2,rep,packed,name=page_rank_shares,json=pageRankShares,proto3" json:"page_rank_shares,omitempty"`
	GraphSize      int32     `protobuf:"varint,3,opt,name=graph_size,json=graphSize,proto3" json:"graph_size,omitempty"`
}

func (x *ReducerInput) Reset() {
	*x = ReducerInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reducer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerInput) ProtoMessage() {}

func (x *ReducerInput) ProtoReflect() protoreflect.Message {
	mi := &file_reducer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerInput.ProtoReflect.Descriptor instead.
func (*ReducerInput) Descriptor() ([]byte, []int) {
	return file_reducer_proto_rawDescGZIP(), []int{0}
}

func (x *ReducerInput) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReducerInput) GetPageRankShares() []float32 {
	if x != nil {
		return x.PageRankShares
	}
	return nil
}

func (x *ReducerInput) GetGraphSize() int32 {
	if x != nil {
		return x.GraphSize
	}
	return 0
}

type ReducerCleanUpInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId          int32   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurrentPageRank float32 `protobuf:"fixed32,2,opt,name=current_page_rank,json=currentPageRank,proto3" json:"current_page_rank,omitempty"`
	GraphSize       int32   `protobuf:"varint,3,opt,name=graph_size,json=graphSize,proto3" json:"graph_size,omitempty"`
	SinkMass        float32 `protobuf:"fixed32,4,opt,name=sink_mass,json=sinkMass,proto3" json:"sink_mass,omitempty"`
}

func (x *ReducerCleanUpInput) Reset() {
	*x = ReducerCleanUpInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reducer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducerCleanUpInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerCleanUpInput) ProtoMessage() {}

func (x *ReducerCleanUpInput) ProtoReflect() protoreflect.Message {
	mi := &file_reducer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerCleanUpInput.ProtoReflect.Descriptor instead.
func (*ReducerCleanUpInput) Descriptor() ([]byte, []int) {
	return file_reducer_proto_rawDescGZIP(), []int{1}
}

func (x *ReducerCleanUpInput) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReducerCleanUpInput) GetCurrentPageRank() float32 {
	if x != nil {
		return x.CurrentPageRank
	}
	return 0
}

func (x *ReducerCleanUpInput) GetGraphSize() int32 {
	if x != nil {
		return x.GraphSize
	}
	return 0
}

func (x *ReducerCleanUpInput) GetSinkMass() float32 {
	if x != nil {
		return x.SinkMass
	}
	return 0
}

type ReducerOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId       int32   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NewRankValue float32 `protobuf:"fixed32,2,opt,name=new_rank_value,json=newRankValue,proto3" json:"new_rank_value,omitempty"`
}

func (x *ReducerOutput) Reset() {
	*x = ReducerOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reducer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducerOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerOutput) ProtoMessage() {}

func (x *ReducerOutput) ProtoReflect() protoreflect.Message {
	mi := &file_reducer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerOutput.ProtoReflect.Descriptor instead.
func (*ReducerOutput) Descriptor() ([]byte, []int) {
	return file_reducer_proto_rawDescGZIP(), []int{2}
}

func (x *ReducerOutput) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReducerOutput) GetNewRankValue() float32 {
	if x != nil {
		return x.NewRankValue
	}
	return 0
}

type ReducerHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive bool `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
}

func (x *ReducerHeartbeatRequest) Reset() {
	*x = ReducerHeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reducer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerHeartbeatRequest) ProtoMessage() {}

func (x *ReducerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reducer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ReducerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_reducer_proto_rawDescGZIP(), []int{3}
}

func (x *ReducerHeartbeatRequest) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type ReducerHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive bool `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
}

func (x *ReducerHeartbeatResponse) Reset() {
	*x = ReducerHeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reducer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReducerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerHeartbeatResponse) ProtoMessage() {}

func (x *ReducerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reducer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ReducerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_reducer_proto_rawDescGZIP(), []int{4}
}

func (x *ReducerHeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_reducer_proto protoreflect.FileDescriptor

var file_reducer_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x70, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x72, 0x61, 0x70, 0x68, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x67, 0x72, 0x61, 0x70, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x69, 0x6e, 0x6b, 0x5f, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x73, 0x69, 0x6e, 0x6b, 0x4d, 0x61, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x0d, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x61, 0x6e, 0x6b,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6e, 0x65,
	0x77, 0x52, 0x61, 0x6e, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x17, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x32, 0x69, 0x0a,
	0x07, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x12, 0x0d, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x35, 0x0a, 0x0d, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x6e,
	0x55, 0x70, 0x12, 0x14, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x55, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x4f, 0x0a, 0x10, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x3b, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reducer_proto_rawDescOnce sync.Once
	file_reducer_proto_rawDescData = file_reducer_proto_rawDesc
)

func file_reducer_proto_rawDescGZIP() []byte {
	file_reducer_proto_rawDescOnce.Do(func() {
		file_reducer_proto_rawDescData = protoimpl.X.CompressGZIP(file_reducer_proto_rawDescData)
	})
	return file_reducer_proto_rawDescData
}

var file_reducer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reducer_proto_goTypes = []interface{}{
	(*ReducerInput)(nil),             // 0: ReducerInput
	(*ReducerCleanUpInput)(nil),      // 1: ReducerCleanUpInput
	(*ReducerOutput)(nil),            // 2: ReducerOutput
	(*ReducerHeartbeatRequest)(nil),  // 3: ReducerHeartbeatRequest
	(*ReducerHeartbeatResponse)(nil), // 4: ReducerHeartbeatResponse
}
var file_reducer_proto_depIdxs = []int32{
	0, // 0: Reducer.Reduce:input_type -> ReducerInput
	1, // 1: Reducer.ReduceCleanUp:input_type -> ReducerCleanUpInput
	3, // 2: ReducerHeartbeat.Ping:input_type -> ReducerHeartbeatRequest
	2, // 3: Reducer.Reduce:output_type -> ReducerOutput
	2, // 4: Reducer.ReduceCleanUp:output_type -> ReducerOutput
	4, // 5: ReducerHeartbeat.Ping:output_type -> ReducerHeartbeatResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reducer_proto_init() }
func file_reducer_proto_init() {
	if File_reducer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reducer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReducerInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reducer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReducerCleanUpInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reducer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReducerOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reducer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReducerHeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reducer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReducerHeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reducer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_reducer_proto_goTypes,
		DependencyIndexes: file_reducer_proto_depIdxs,
		MessageInfos:      file_reducer_proto_msgTypes,
	}.Build()
	File_reducer_proto = out.File
	file_reducer_proto_rawDesc = nil
	file_reducer_proto_goTypes = nil
	file_reducer_proto_depIdxs = nil
}
